---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mice.mcerror

<!-- badges: start -->
<!-- badges: end -->

The {mice.mcerror} package is an add-on package to {[mice](https://CRAN.R-project.org/package=mice)} that can be used to calculate Monte Carlo error estimates for statistics computed using multiply imputed data.

## Installation

You can install the development version of {mice.mcerror} from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ellessenne/mice.mcerror")
```

# Comparison with Stata

We replicate the following example from Stata:

```stata
use http://www.stata-press.com/data/r14/mheart1s20

mi estimate, dots mcerror: logit attack smokes age bmi hsgrad female
```

```{r}
library(mice)
data("mheart1s20.mice")

fit <- with(
  data = mheart1s20.mice,
  expr = glm(
    formula = attack ~ smokes + age + bmi + hsgrad + female,
    family = binomial(link = "logit")
  )
)
summary(pool(fit))
```
